import { ShadowBox } from "../ShadowBox/ShadowBox";
import shadowLogo from "../assets/svg/shadowLogo.svg";

export const ShadowBoxLayer = () => {
    return (
        <>
            <ShadowBox stylesBox={{
                "width": "40px",
                "height": "40px",
                "right": "53px",
                "bottom": "294px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "right": "399px",
                "bottom": "285px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "right": "367px",
                "bottom": "285px",
            }} />
            <ShadowBox stylesBox={{
                "width": "232px",
                "height": "8px",
                "left": "102px",
                "bottom": "305px",
            }} />
            <ShadowBox stylesBox={{
                "width": "80px",
                "height": "8px",
                "left": "100px",
                "bottom": "364px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "left": "102px",
                "top": "430px",
            }} />
            <ShadowBox stylesBox={{
                "width": "40px",
                "height": "8px",
                "left": "102px",
                "top": "192px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "left": "389px",
                "top": "93px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "left": "421px",
                "top": "93px",
            }} />
            <ShadowBox stylesBox={{
                "width": "40px",
                "height": "40px",
                "left": "831px",
                "top": "92px",
            }} />
            <ShadowBox stylesBox={{
                "width": "40px",
                "height": "40px",
                "left": "997px",
                "bottom": "368px",
            }} />
            <ShadowBox stylesBox={{
                "width": "24px",
                "height": "8px",
                "left": "1551px",
                "top": "186px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "left": "1573px",
                "top": "302px",
            }} />
            <ShadowBox stylesBox={{
                "width": "80px",
                "height": "8px",
                "left": "1507px",
                "bottom": "665px",
            }} />
            <ShadowBox stylesBox={{
                "width": "8px",
                "height": "8px",
                "left": "1579px",
                "bottom": "549px",
            }} />
            <ShadowBox stylesBox={{
                "width": "232px",
                "height": "8px",
                "right": "461px",
                "top": "70px",
            }} />
            <ShadowBox stylesBox={{
                "width": "40px",
                "height": "40px",
                "left": "2126px",
                "top": "402px",
            }} />
            <ShadowBox stylesBox={{
                "width": "61px",
                "height": "8px",
                "right": "357px",
                "top": "710px",
            }} />
            <ShadowBox stylesBox={{
                "width": "80px",
                "height": "80px",
                "left": "100px",
                "bottom": "382px",
                "display": "flex",
                "justify-content": "center",
                "align-items": "center"
            }} children={<img src={shadowLogo} alt='shadow logo'/> }
            />
            
        </>
    )
}